### ISSUE TITLE
上传出错？

### ISSUE THREAD

**Issue by ningyuwhut** [jinfagang/gooooup#1]
我在上传一张图片时出现下面的log，貌似是出问题了，帮忙看下哈
gooooup - upload images(files) to cloud for bedding.

  ____  ___   ___   ___   ___  _   _ ____
 / _  |/ _ \ / _ \ / _ \ / _ \| | | |  _ \
( (_| | |_| | |_| | |_| | |_| | |_| | |_| |
 \___ |\___/ \___/ \___/ \___/|____/|  __/
(_____|                             |_|
Author JinTian. @wechat: jintianiloveu
gooooup will upload image to sms: https://sm.ms
upload success!
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.main()
	/Volumes/xs/CodeSpace/Weapons/gooooup/main.go:76 +0x1069

**Comment by lucasjinreal** [comment]
是最新的不，你只需要gooooup 然后把图片拖到terminal就可以，也就是后面带一个图片路径

**Comment by lucasjinreal** [comment]
gooooup will upload image to sms: https://sm.ms
upload success!
url: https://i.loli.net/2017/09/05/59ae528237413.jpeg
Done! just paste it!

**Comment by ningyuwhut** [comment]
貌似跟图片有关，换了一张图片就没问题
![neural_net](https://user-images.githubusercontent.com/1762074/30057256-9787cf28-9268-11e7-8224-dc33468d4a7b.jpeg)

**Comment by ningyuwhut** [comment]
不好意思，是我弄错了，我上传了一张不是图片的文件，sorry
